### ISSUE TITLE
ProGuard Error

### ISSUE THREAD

**Issue by vijaybhairavjibhaiaslaliya** [dandar3/android-google-play-services-ads-lite#1]
```
[2017-06-22 12:40:56 - demo] Proguard returned with error code 1. See console
[2017-06-22 12:40:56 - demo] java.io.IOException: Can't read [E:\android-sdk-windows-orijnal\android-sdk-windows\platforms\android-25\android.jar] (Can't process class [java/text/CollationElementIterator.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7)))
[2017-06-22 12:40:56 - demo] 	at proguard.InputReader.readInput(InputReader.java:230)
[2017-06-22 12:40:56 - demo] 	at proguard.InputReader.readInput(InputReader.java:200)
[2017-06-22 12:40:56 - demo] 	at proguard.InputReader.readInput(InputReader.java:178)
[2017-06-22 12:40:56 - demo] 	at proguard.InputReader.execute(InputReader.java:100)
[2017-06-22 12:40:56 - demo] 	at proguard.ProGuard.readInput(ProGuard.java:196)
[2017-06-22 12:40:56 - demo] 	at proguard.ProGuard.execute(ProGuard.java:78)
[2017-06-22 12:40:56 - demo] 	at proguard.ProGuard.main(ProGuard.java:492)
[2017-06-22 12:40:56 - demo] Caused by: java.io.IOException: Can't process class [java/text/CollationElementIterator.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7))
[2017-06-22 12:40:56 - demo] 	at proguard.io.ClassReader.read(ClassReader.java:112)
[2017-06-22 12:40:56 - demo] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[2017-06-22 12:40:56 - demo] 	at proguard.io.JarReader.read(JarReader.java:65)
[2017-06-22 12:40:56 - demo] 	at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
[2017-06-22 12:40:56 - demo] 	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
[2017-06-22 12:40:56 - demo] 	at proguard.InputReader.readInput(InputReader.java:226)
[2017-06-22 12:40:56 - demo] 	... 6 more
[2017-06-22 12:40:56 - demo] Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [52.0] (maximum 51.0, Java 1.7)
[2017-06-22 12:40:56 - demo] 	at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:140)
[2017-06-22 12:40:56 - demo] 	at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:89)
[2017-06-22 12:40:56 - demo] 	at proguard.classfile.LibraryClass.accept(LibraryClass.java:301)
[2017-06-22 12:40:56 - demo] 	at proguard.io.ClassReader.read(ClassReader.java:86)
[2017-06-22 12:40:56 - demo] 	... 11 more
```

**Comment by dandar3** [comment]
Closing as duplicate - https://github.com/dandar3/android-google-play-services-ads/issues/3
